name: sar-pretrain
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.1.2
  - torchvision=0.16.2
  - pytorch-cuda=12.1
  - pip
  - pip:
      - timm==0.4.12
      - easydict==1.13
      - numpy==1.26.4
      - Pillow==10.4.0
      - tensorboard==2.17.1
      - scipy==1.13.1
